### ISSUE TITLE
NullPointerException in MonetPreparedStatement.setObject with batch execution

### ISSUE THREAD

**Issue by Guillaume789** [MonetDBSolutions/MonetDBe-Java#3]
Hi,

I am using a prepared statement to populate a temporary table.
When using a batch size of 5000 I have below null pointer exception.
However, if I set the batch size to 1 (no batch execution, but execute statement each time) I do not have this null pointer exception.

Message:
    java.lang.NullPointerException
Level:
    SEVERE
Stack Trace:
null
    org.monetdb.monetdbe.MonetPreparedStatement.setObject(MonetPreparedStatement.java:709)
    org.monetdb.monetdbe.MonetPreparedStatement.executeBatch(MonetPreparedStatement.java:209)
    org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242)
    org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242)
    com.finboxsolutions.easyrec.appender.utils.PreparedStatementWrapper.executeBatch(PreparedStatementWrapper.java:519)
    com.finboxsolutions.easyrec.appender.utils.PreparedStatementWrapper.close(PreparedStatementWrapper.java:547)
    com.finboxsolutions.easyrec.appender.CubeDatabaseAppender.close(CubeDatabaseAppender.java:126)

Thanks,
Guillaume

[hs_err_pid3488.log](https://github.com/MonetDBSolutions/MonetDBe-Java/files/6416093/hs_err_pid3488.log)

**Comment by Guillaume789** [comment]
Hi, could this issue also be fixed by fix c3e34f8 ?
I will try to run new tests.
Thanks, Guillaume

**Comment by Guillaume789** [comment]
Hi, 
I have done another test with latest SNAPSHOT release and I still can reproduce the crash.
Regards, Guillaume

**Comment by bernardom29** [comment]
I've left you an update message on issue #4 , I'll be working on the fix to both these Windows bugs this week. Today I don't have access to the Windows desktop machine I was using to test it, but you'll get an update before the end of the week.

**Comment by bernardom29** [comment]
I believe this is fixed in the latest Windows SNAPSHOT release. This issue happened because of a type error in builds with no 128 bit integers, which the Windows build has disabled for now.

Whenever you have the time, please confirm if you no longer have this error :)

**Comment by Guillaume789** [comment]
Hi,

I have tested with the latest SNAPSHOT release and I can still reproduce the crash:

    java.lang.NullPointerException
    org.monetdb.monetdbe.MonetPreparedStatement.executeBatch(MonetPreparedStatement.java:235)
    org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242)
    org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242)
    com.finboxsolutions.easyrec.appender.utils.PreparedStatementWrapper.executeBatch(PreparedStatementWrapper.java:515)


I have also tested with Jar: **monetdbe-java-1.0-20210521.084046-64-windows.jar** and I can also reproduce the crash.

Regards,
Guillaume

**Comment by njnes** [comment]
Could you create a mini java program resembling your problem?. Or describe the schema/table and insert statement your using?
